site_name: Grupo de Estudos Ecologia e Marxismo
repo_url: https://github.com/Ecomarx/ecomarx.github.io
theme:
  name: material
  palette:
    primary: green
  features:
    - navigation.tabs
  language: pt
markdown_extensions:
  - footnotes
nav:
  - "Sobre": 
    - index.md
  - "Ciclos de Estudo":
    - ciclos.md
    - "2ᵒ Ciclo - Junho a Agosto, 2021": 2o-ciclo/index.md
    - "6ᵒ Ciclo - Julho a Setembro, 2022":
      - 6o-ciclo/index.md
      - 6o-ciclo/referencias.md
      - 6o-ciclo/1o-encontro.md
      - 6o-ciclo/2o-encontro.md
      - 6o-ciclo/3o-encontro.md
      - 6o-ciclo/4o-encontro.md
      - 6o-ciclo/5o-encontro.md
      - 6o-ciclo/6o-encontro.md
      - 6o-ciclo/7o-encontro.md
    - "7ᵒ Ciclo - Março a Maio, 2022": 7o-ciclo/index.md
  - Material:
    - material/index.md
    - material/glossario.md
    - material/podcasts.md
  - CONTRIBUTING.md
  - SUPPORT.md
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/GEcomarx
      name: EcoMarx no Twitter
    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/geecomarx/
      name: EcoMarx no Instagram
    - icon: fontawesome/brands/whatsapp
      link: https://chat.whatsapp.com/EHNP8AwJ7Hd256XQjZjDMg
      name: Canal de Informes no Whatsapp
    - icon: fontawesome/brands/telegram
      link: https://t.me/geecomarxcanal
      name: Canal de Informes no Telegram